version: "3.8"

services:
  python:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    restart: unless-stopped
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ~/apps/overbot/database:/var/lib/postgresql/data
      - ~/apps/overbot/logs:/app/logs
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
        ]
      interval: 10s
      timeout: 3s
      retries: 3
