version: "3.8"

services:
  python:
    restart: unless-stopped
    build: .
    volumes:
      - ~/apps/overbot/logs:/app/logs
      - ./.git:/app/.git # used by pygit2
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    restart: unless-stopped
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ~/apps/overbot/database:/var/lib/postgresql/data
      - ./migrations/V1_Migration.sql:/docker-entrypoint-initdb.d/V1.sql
      - ./migrations/V2_Migration.sql:/docker-entrypoint-initdb.d/V2.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
        ]
      interval: 10s
      timeout: 3s
      retries: 3
